version = 1

[merge]
require_automerge_label = false
#automerge_label = 'automerge 🤞'

# https://kodiakhq.com/docs/recipes#better-merge-messages
[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
body_type = "markdown"
strip_html_comments = true
